// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI2iwObVqRZj4kebNRnqm0OdAzk0M6fsY',
    appId: '1:777643485677:web:a79719ec5320236ed49fe4',
    messagingSenderId: '777643485677',
    projectId: 'authtutorial-flutter',
    authDomain: 'authtutorial-flutter.firebaseapp.com',
    storageBucket: 'authtutorial-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF_tM1wh7hCL5gZmp_-Ma87FEtrpGeXYo',
    appId: '1:777643485677:android:074a4c0755bab2f1d49fe4',
    messagingSenderId: '777643485677',
    projectId: 'authtutorial-flutter',
    storageBucket: 'authtutorial-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD55qnI8_hM5te1BYk3kSEfDXedMQ8vgos',
    appId: '1:777643485677:ios:51176f6f997c5925d49fe4',
    messagingSenderId: '777643485677',
    projectId: 'authtutorial-flutter',
    storageBucket: 'authtutorial-flutter.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD55qnI8_hM5te1BYk3kSEfDXedMQ8vgos',
    appId: '1:777643485677:ios:51176f6f997c5925d49fe4',
    messagingSenderId: '777643485677',
    projectId: 'authtutorial-flutter',
    storageBucket: 'authtutorial-flutter.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI2iwObVqRZj4kebNRnqm0OdAzk0M6fsY',
    appId: '1:777643485677:web:36c7fe39d6c953f1d49fe4',
    messagingSenderId: '777643485677',
    projectId: 'authtutorial-flutter',
    authDomain: 'authtutorial-flutter.firebaseapp.com',
    storageBucket: 'authtutorial-flutter.firebasestorage.app',
  );
}
